### ISSUE TITLE
Provide a README.md and make `gh-pages` branch as default

### ISSUE THREAD

**Issue by andygrunwald** [henryr/distributed-systems-readings#1]
Hey,

nice collection! Thanks for this.
I found this repository before and closed the tab, because i thought it was empty.
Luckily i found your github-pages: http://henryr.github.io/distributed-systems-readings/

To avoid the first impression i suggest to make the `gh-pages` branch as default branch (or delete the master branch) and provide a README.md in the repository to link to http://henryr.github.io/distributed-systems-readings/

And add http://henryr.github.io/distributed-systems-readings/ into the description :)

I think with this tipps you can reach more people, because this list deserves it!

**Comment by rohitsm** [comment]
Great suggestion. I actually had a little bit of a problem finding the URL for the Github page. Thanks @andygrunwald for posting the link here.  :-)

**Comment by rohitsm** [comment]
I did that and left a pull request here: https://github.com/henryr/distributed-systems-readings/pull/2

Thanks again for compiling the list @henryr. Appreciate it. :)

**Comment by andygrunwald** [comment]
Thank you @rohitsm!
